/**
 * Plays a looping MP3 generated by Google Lyria.
 * Uses Web Audio API's MediaElementSourceNode + GainNode so the music
 * can be smoothly faded in/out when voice feedback plays.
 */
export class LyriaPlayer {
  private audioEl: HTMLAudioElement | null = null;
  private ctx: AudioContext | null = null;
  private gainNode: GainNode | null = null;

  /** Load a base64-encoded MP3 and prepare it for looping playback. */
  load(base64: string, mimeType: string): void {
    this.close();

    const dataUrl = `data:${mimeType};base64,${base64}`;
    this.audioEl = new Audio(dataUrl);
    this.audioEl.loop = true;

    this.ctx = new AudioContext();
    this.gainNode = this.ctx.createGain();
    this.gainNode.connect(this.ctx.destination);

    const src = this.ctx.createMediaElementSource(this.audioEl);
    src.connect(this.gainNode);
  }

  /** Unlock AudioContext and start playback. Call from a user-gesture handler. */
  async play(): Promise<void> {
    if (!this.audioEl || !this.ctx) return;
    if (this.ctx.state === "suspended") await this.ctx.resume();
    try {
      await this.audioEl.play();
    } catch {
      // Autoplay blocked — will retry on next user interaction
    }
  }

  /**
   * Resume if audio was blocked by autoplay policy.
   * Call this from any user interaction (click, touch).
   */
  async resume(): Promise<void> {
    return this.play();
  }

  pause(): void {
    this.audioEl?.pause();
  }

  unpause(): void {
    if (this.audioEl && this.ctx) {
      if (this.ctx.state === "suspended") void this.ctx.resume();
      void this.audioEl.play().catch(() => {});
    }
  }

  fadeOut(durationSec = 0.5): void {
    if (!this.ctx || !this.gainNode) return;
    const gain = this.gainNode;
    gain.gain.cancelScheduledValues(this.ctx.currentTime);
    gain.gain.setValueAtTime(gain.gain.value, this.ctx.currentTime);
    gain.gain.linearRampToValueAtTime(0, this.ctx.currentTime + durationSec);
  }

  fadeIn(durationSec = 1.0): void {
    if (!this.ctx || !this.gainNode) return;
    const gain = this.gainNode;
    gain.gain.cancelScheduledValues(this.ctx.currentTime);
    gain.gain.setValueAtTime(gain.gain.value, this.ctx.currentTime);
    gain.gain.linearRampToValueAtTime(1, this.ctx.currentTime + durationSec);
  }

  close(): void {
    this.audioEl?.pause();
    this.audioEl = null;
    void this.ctx?.close();
    this.ctx = null;
    this.gainNode = null;
  }
}
